### ISSUE TITLE
Call Graph generation in FASTEN format using pycg

### ISSUE THREAD

**Issue by amphioxis** [fasten-project/fasten-pypi-plugin#7]
Hi @vitsalis 

Currently the `pypi-Plugin` is able to create Call Graphs using [`pycg`](https://github.com/vitsalis/pycg) for locally stored packages (which are not in the FASTEN database).

However I am facing problems concerning the [`internal` key](https://github.com/fasten-project/fasten-pypi-plugin/blob/cb9d18e1208c9f80f85b7c2d8e66ec5e755c007e/src/fasten/callGraphs/cryptography-3.4.7.json#L9) which is missing in the [Call Graphs](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/src/fasten/callGraphs/fasten-pypi-plugin.json) created by the `pypi-plugin` (and [`pycg-stitch`](https://github.com/fasten-project/pycg-stitch) is complaining about its missing).

I am not sure if I use `pycg` in the correct way. I tried to create a Call Graph for the [`cryptography`](https://github.com/pyca/cryptography) package but that is giving me
```
File "pypi-Plugin-venv/lib/python3.9/site-packages/pycg/processing/base.py", line 184, in do_assign
    if pos < len(decoded):
TypeError: object of type 'Definition' has no len()
```
with both, the Call Graph generation using the `pypi-plugin` or running `pycg` as command line tool via
```
pycg --package cryptography --fasten --product "cryptography" --forge "PyPI" --version "0.1" --timestamp 42 (find cryptography -type f -name "*.py") -o crypto.json
```

What am I doing wrong?
Thanks for help!

**Comment by gdrosos** [comment]
The internal key error is due to the fact that PyCG alone creates call graphs following the RCG version 1 format (https://github.com/fasten-project/fasten/wiki/Revision-Call-Graph-format#version-1-1) while the PyCG Stitch uses RCGs following the version 2 format (https://github.com/fasten-project/fasten/wiki/Revision-Call-Graph-format#version-2-1). Therefore, for stitching, the version 1 rcgs  need to be converted to version 2. The tool responsible for this convertion can be found on the pypi-tools repo: https://github.com/fasten-project/pypi-tools/tree/master/cg-producer

**Comment by amphioxis** [comment]
Closed because `pycg` is creating Call Graphs in the right format now.
